-- MigraciÃ³n Inicial para CampaÃ±a de DinamizaciÃ³n (Supabase PostgreSQL)
-- Cumplimiento de requerimientos: 1-5M registros, MÃ¡quina de estados, Ley 1581 (Habeas Data).

-- 1. Tabla de ConfiguraciÃ³n de CampaÃ±a
CREATE TABLE public.configuracion_campana (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre_campana VARCHAR(255) NOT NULL,
    landing_slug VARCHAR(255) UNIQUE NOT NULL,
    activa BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Premios (InyecciÃ³n DinÃ¡mica)
-- Permite que el Dashboard administre los premios y el frontend consulte en tiempo real.
CREATE TABLE public.premios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campana_id UUID REFERENCES public.configuracion_campana(id) ON DELETE CASCADE,
    nombre_premio VARCHAR(255) NOT NULL,
    descripcion TEXT,
    cantidad_disponible INTEGER NOT NULL DEFAULT 0 CHECK (cantidad_disponible >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Boletas (Optimizada para 5M de registros)
-- Estados: 0=CREADA, 1=IMPRESA, 2=ACTIVA, 3=REGISTRADA, 4=CERRADA
CREATE TABLE public.boletas (
    id_boleta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campana_id UUID REFERENCES public.configuracion_campana(id),
    
    -- Uso de SMALLINT con CHECK constraint en lugar de Enum para eficiencia en bÃºsquedas sobre millones de filas.
    estado SMALLINT NOT NULL DEFAULT 0 CHECK (estado BETWEEN 0 AND 4),
    
    -- Token Ãºnico de integridad para prevenir ataques
    token_integridad VARCHAR(255) UNIQUE NOT NULL,
    
    -- Campos capturados en el proceso
    identificacion_usuario VARCHAR(50),
    nombre_usuario VARCHAR(255),
    celular_usuario VARCHAR(20),
    
    -- Checkbox obligatorio Habeas Data (Ley 1581 Colombiana)
    habeas_data_aceptado BOOLEAN DEFAULT false,
    
    -- Premio seleccionado inyectado en el Landing
    premio_seleccionado UUID REFERENCES public.premios(id),
    
    -- Datos operativos para ranking y analÃ­tica
    zona_comercio VARCHAR(255),
    ip_registro INET,
    
    -- Trazabilidad de tiempos
    fecha_activacion TIMESTAMPTZ,
    fecha_registro TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ãndices B-Tree eficientes para lectura con volÃºmenes de 5M+ de filas
CREATE INDEX idx_boletas_estado ON public.boletas(estado);
CREATE INDEX idx_boletas_token ON public.boletas(token_integridad);
CREATE INDEX idx_boletas_campana ON public.boletas(campana_id);

-- 4. FunciÃ³n y MÃ¡quina de Estados (Triple Candado de Seguridad)
CREATE OR REPLACE FUNCTION auditar_estado_boleta()
RETURNS TRIGGER AS $$
BEGIN
    -- LÃ³gica de transiciÃ³n de estado hacia REGISTRADA (3)
    IF NEW.estado = 3 THEN
        
        -- Candado 1: El estado inmediatamente anterior DEBE ser ACTIVA (2)
        IF OLD.estado != 2 THEN
            RAISE EXCEPTION 'ViolaciÃ³n de SEGURIDAD: La boleta % no puede ser REGISTRADA sin estar previamente ACTIVA en punto de venta. Estado anterior: %', NEW.id_boleta, OLD.estado;
        END IF;

        -- Candado 2: Cumplimiento Ley 1581 (Habeas Data) obligatorio
        IF NEW.habeas_data_aceptado IS NOT TRUE THEN
            RAISE EXCEPTION 'ViolaciÃ³n de POLÃTICA DE DATOS: La boleta % requiere la aceptaciÃ³n expresa de las polÃ­ticas de privacidad y tratamiento de datos (Ley 1581).', NEW.id_boleta;
        END IF;

        -- Candado 3: SelecciÃ³n de premio obligatoria (consulta al menÃº desplegable)
        IF NEW.premio_seleccionado IS NULL THEN
            RAISE EXCEPTION 'ViolaciÃ³n de REGLA NEGOCIO: La boleta % no ha seleccionado un premio dinÃ¡mico.', NEW.id_boleta;
        END IF;

        -- Setear el timestamp exacto del registro
        NEW.fecha_registro = NOW();
    END IF;

    -- Registrar Timestamp cuando se activa la boleta (Estado 2)
    IF NEW.estado = 2 AND OLD.estado != 2 THEN
        NEW.fecha_activacion = NOW();
    END IF;

    -- ActualizaciÃ³n de Ãºltimo cambio
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. Trigger
CREATE TRIGGER trg_maquina_estados_boletas
BEFORE UPDATE ON public.boletas
FOR EACH ROW
EXECUTE FUNCTION auditar_estado_boleta();

-- 6. ConfiguraciÃ³n de Seguridad RLS
ALTER TABLE public.configuracion_campana ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.premios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boletas ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas de Lectura (Edge Access)
-- Permite que el Landing Page consulte campaÃ±as activas
CREATE POLICY "Lectura pÃºblica de configuracion activa" 
ON public.configuracion_campana FOR SELECT USING (activa = true);

-- Permite consultar los premios disponibles solo de las campaÃ±as activas
CREATE POLICY "Lectura pÃºblica de premios disponibles" 
ON public.premios FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.configuracion_campana 
        WHERE id = premios.campana_id AND activa = true
    )
);

-- Acceso cerrado al cliente: Boletas solo se consultan/registran a travÃ©s de 
-- Supabase Edge Functions con la llave 'Service Role'
CREATE POLICY "Boletas bloqueadas a lectura anonima" 
ON public.boletas FOR ALL USING (false);
-- PolÃ­tica temporal para visualizaciÃ³n por Websocket en Frontend
CREATE POLICY "Dashboard puede leer boletas" 
ON public.boletas FOR SELECT USING (true);

-- Habilitar Supabase Realtime para la tabla
ALTER PUBLICATION supabase_realtime ADD TABLE public.boletas;
-- 1. DefiniciÃ³n de Rol e InstanciaciÃ³n de Perfiles
CREATE TYPE rol_usuario AS ENUM ('admin', 'distribuidor', 'operativo');

CREATE TABLE public.perfiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    rol rol_usuario NOT NULL DEFAULT 'distribuidor',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS en perfiles
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;

-- Policy simplificada para evitar infinite recursion y devolver su propio perfil de forma segura
-- Policy ampliada para que la UI operativa de Asignaciones pueda leer los perfiles (Distribuidores)
CREATE POLICY "Visibilidad Publica Autenticada de Perfiles"
ON public.perfiles FOR SELECT USING (auth.role() = 'authenticated');

-- 2. EvoluciÃ³n de la Tabla Boletas (LogÃ­stica y Trazabilidad)
ALTER TABLE public.boletas 
ADD COLUMN distribuidor_id UUID REFERENCES public.perfiles(id),
ADD COLUMN comercio_nombre VARCHAR(255),
ADD COLUMN fecha_despacho TIMESTAMPTZ;

-- 3. MÃ¡quina de Estados Estricta (EvoluciÃ³n de auditar_estado_boleta)
CREATE OR REPLACE FUNCTION auditar_estado_boleta()
RETURNS TRIGGER AS $$
BEGIN
    -- Estado 1 (Despachada al Distribuidor): Viene de 0
    IF NEW.estado = 1 THEN
        IF OLD.estado != 0 THEN
            RAISE EXCEPTION 'MÃQUINA DE ESTADOS: Boleta % no puede ser DESPACHADA si no estaba en BODEGA (0).', NEW.id_boleta;
        END IF;
        IF NEW.distribuidor_id IS NULL THEN
            RAISE EXCEPTION 'LOGÃSTICA: Boleta % despachada sin distribuidor asignado.', NEW.id_boleta;
        END IF;
        -- Registrar fecha de despacho
        IF OLD.estado != 1 THEN
            NEW.fecha_despacho = NOW();
        END IF;
    END IF;

    -- Estado 2 (Activa en Comercio): Viene de 1
    IF NEW.estado = 2 THEN
        IF OLD.estado != 1 THEN
            RAISE EXCEPTION 'MÃQUINA DE ESTADOS: Boleta % no puede ser ACTIVA en punto de venta sin haber sido despachada previamente al distribuidor (Estado 1).', NEW.id_boleta;
        END IF;
        IF NEW.comercio_nombre IS NULL THEN
            RAISE EXCEPTION 'LOGÃSTICA: Falta el nombre del comercio final para activar boleta %.', NEW.id_boleta;
        END IF;
        -- Registrar fecha si es la primera vez que se activa
        IF OLD.estado != 2 THEN
            NEW.fecha_activacion = NOW();
        END IF;
    END IF;

    -- LÃ³gica de transiciÃ³n de estado hacia REGISTRADA (3)
    IF NEW.estado = 3 THEN
        -- Candado 1: El estado inmediatamente anterior DEBE ser ACTIVA (2)
        IF OLD.estado != 2 THEN
            RAISE EXCEPTION 'ViolaciÃ³n de SEGURIDAD: La boleta % no puede ser REGISTRADA sin estar previamente ACTIVA en punto de venta. Estado anterior: %', NEW.id_boleta, OLD.estado;
        END IF;

        -- Candado 2: Cumplimiento Ley 1581 (Habeas Data) obligatorio
        IF NEW.habeas_data_aceptado IS NOT TRUE THEN
            RAISE EXCEPTION 'ViolaciÃ³n de POLÃTICA DE DATOS: La boleta % requiere la aceptaciÃ³n expresa de las polÃ­ticas de privacidad y tratamiento de datos (Ley 1581).', NEW.id_boleta;
        END IF;

        -- Candado 3: SelecciÃ³n de premio obligatoria (consulta al menÃº desplegable)
        IF NEW.premio_seleccionado IS NULL THEN
            RAISE EXCEPTION 'ViolaciÃ³n de REGLA NEGOCIO: La boleta % no ha seleccionado un premio dinÃ¡mico.', NEW.id_boleta;
        END IF;

        -- Setear el timestamp exacto del registro
        NEW.fecha_registro = NOW();
    END IF;

    -- ActualizaciÃ³n de Ãºltimo cambio
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Funciones Operativas Aseguradas por Base de Datos

-- RPC Para Asignar Masivamente (Auditado DB-First)
CREATE OR REPLACE FUNCTION asignar_lote_boletas(p_admin_id UUID, p_dist_id UUID, p_rango_inicio BIGINT, p_rango_fin BIGINT)
RETURNS INTEGER AS $$
DECLARE
    tiene_permiso BOOLEAN;
    filas_afectadas INTEGER;
BEGIN
    -- AuditorÃ­a DB-First: Permite rol 'admin' u 'operativo' asignar lotes
    SELECT EXISTS (
        SELECT 1 FROM public.perfiles 
        WHERE id = p_admin_id AND rol IN ('admin', 'operativo')
    ) INTO tiene_permiso;
    
    IF NOT tiene_permiso THEN
        RAISE EXCEPTION 'SEGURIDAD: OperaciÃ³n denegada. El ID proporcionado no posee permisos de asignaciÃ³n (admin u operativo).';
    END IF;

    -- MutaciÃ³n masiva usando la mÃ¡quina de estados. Modifica solo las de estado 0.
    UPDATE public.boletas 
    SET 
        estado = 1,
        distribuidor_id = p_dist_id
    WHERE id_boleta BETWEEN p_rango_inicio AND p_rango_fin
      AND estado = 0;

    GET DIAGNOSTICS filas_afectadas = ROW_COUNT;
    RETURN filas_afectadas;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC Para Activar Unitaria en Punto Venta
CREATE OR REPLACE FUNCTION activar_boleta_comercio(p_dist_id UUID, p_boleta_id BIGINT, p_nombre_comercio VARCHAR)
RETURNS BOOLEAN AS $$
DECLARE
    filas_afectadas INTEGER;
BEGIN
    UPDATE public.boletas 
    SET 
        estado = 2,
        comercio_nombre = p_nombre_comercio,
        zona_comercio = (SELECT zona FROM public.perfiles WHERE id = p_dist_id LIMIT 1) -- Opcional: auto heredar zona
    WHERE id_boleta = p_boleta_id
      AND distribuidor_id = p_dist_id
      AND estado = 1;

    GET DIAGNOSTICS filas_afectadas = ROW_COUNT;
    
    IF filas_afectadas = 0 THEN
        RAISE EXCEPTION 'No se pudo activar la boleta. Verifique que no haya sido activada ya, o que usted sea su propietario.';
    END IF;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 5. RLS Distribuidor
CREATE POLICY "Distribuidor puede leer su propio inventario de boletas" 
ON public.boletas FOR SELECT USING (distribuidor_id = auth.uid());
-- MÃ³dulo Zonas y MigraciÃ³n Relacional de Perfiles

-- 1. Tabla de CatÃ¡logo de Zonas
CREATE TABLE public.zonas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre VARCHAR(255) UNIQUE NOT NULL,
    descripcion TEXT,
    activa BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Zonas: Solo lectura pÃºblica para usuarios autenticados, y gestiÃ³n de admin real si fuesen a insertarla (desde app)
ALTER TABLE public.zonas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura Autenticada Zonas" ON public.zonas FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "GestiÃ³n Admin Zonas" ON public.zonas 
  FOR ALL USING ((SELECT rol FROM public.perfiles WHERE id = auth.uid()) = 'admin');

-- 2. ModificaciÃ³n Estructural de Perfiles
-- Se agrega en bloque y se migra:
ALTER TABLE public.perfiles 
  ADD COLUMN cedula VARCHAR(50) UNIQUE,
  ADD COLUMN movil VARCHAR(50),
  ADD COLUMN direccion TEXT,
  ADD COLUMN zona_id UUID REFERENCES public.zonas(id) ON DELETE SET NULL;

-- 3. TransiciÃ³n de Datos (zona_id es la nueva fuente de verdad. La columna texto 'zona' ya fue eliminada del schema original.)


-- 4. Modificar RPC activar_boleta_comercio (Si dependÃ­a de la zona heredada)
CREATE OR REPLACE FUNCTION activar_boleta_comercio(p_dist_id UUID, p_boleta_id BIGINT, p_nombre_comercio VARCHAR)
RETURNS BOOLEAN AS $$
DECLARE
    filas_afectadas INTEGER;
    v_zona_nombre VARCHAR;
BEGIN
    -- Capturar nombre de la zona relacionada antes de la activaciÃ³n heredada
    SELECT z.nombre INTO v_zona_nombre 
    FROM public.perfiles p
    JOIN public.zonas z ON p.zona_id = z.id
    WHERE p.id = p_dist_id LIMIT 1;

    UPDATE public.boletas 
    SET 
        estado = 2,
        comercio_nombre = p_nombre_comercio,
        zona_comercio = v_zona_nombre
    WHERE id_boleta = p_boleta_id
      AND distribuidor_id = p_dist_id
      AND estado = 1;

    GET DIAGNOSTICS filas_afectadas = ROW_COUNT;
    
    IF filas_afectadas = 0 THEN
        RAISE EXCEPTION 'No se pudo activar la boleta. Verifique que no haya sido activada ya, o que usted sea su propietario.';
    END IF;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- MIGRACIÃ“N OBSOLETA: El rol 'operativo' fue incorporado directamente en el ENUM
-- original de la migraciÃ³n 20260405210000_jerarquia_estados.sql.
-- Este archivo se conserva solo como referencia histÃ³rica de la decisiÃ³n de diseÃ±o.
-- No ejecuta ninguna sentencia SQL.
-- =====================================================================
-- MigraciÃ³n: AuditorÃ­a de Personal y Trazabilidad Completa
-- =====================================================================

-- 1. Agregar campo de trazabilidad de quiÃ©n despachÃ³ la boleta
ALTER TABLE public.boletas
  ADD COLUMN IF NOT EXISTS asignado_por UUID REFERENCES public.perfiles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_boletas_asignado_por ON public.boletas(asignado_por);
CREATE INDEX IF NOT EXISTS idx_boletas_distribuidor ON public.boletas(distribuidor_id);

-- 2. RLS: Permitir lectura de boletas para usuarios autenticados con rol admin/operativo
--    (La policy original bloquea todo con USING(false); la reemplazamos con una mÃ¡s inteligente)
DROP POLICY IF EXISTS "Boletas bloqueadas a lectura anonima" ON public.boletas;

CREATE POLICY "Lectura de boletas para personal autorizado"
ON public.boletas FOR SELECT USING (
  auth.role() = 'authenticated' AND (
    EXISTS (
      SELECT 1 FROM public.perfiles
      WHERE id = auth.uid() AND rol IN ('admin', 'operativo')
    )
    OR distribuidor_id = auth.uid()
  )
);

CREATE POLICY "Escritura controlada por Service Role y RPC"
ON public.boletas FOR ALL USING (auth.role() = 'service_role');

-- 3. RPC Buscador de Trazabilidad Completa
-- Acepta: nÃºmero de boleta (ej. "5005") o cÃ©dula del cliente (ej. "1144000111")
CREATE OR REPLACE FUNCTION buscar_trazabilidad(p_query TEXT)
RETURNS TABLE (
  id_boleta             BIGINT,
  token_boleta          TEXT,
  estado                SMALLINT,
  estado_label          TEXT,
  -- QuiÃ©n despachÃ³
  asignado_por_nombre   TEXT,
  asignado_por_rol      TEXT,
  -- Distribuidor
  distribuidor_nombre   TEXT,
  distribuidor_zona     TEXT,
  distribuidor_movil    TEXT,
  -- Comercio
  comercio_nombre       TEXT,
  zona_comercio         TEXT,
  fecha_despacho       TIMESTAMPTZ,
  fecha_activacion      TIMESTAMPTZ,
  -- Cliente final (Landing)
  nombre_cliente        TEXT,
  cedula_cliente        TEXT,
  telefono_cliente      TEXT,
  fecha_registro        TIMESTAMPTZ,
  -- Premio
  premio_nombre         TEXT
) AS $$
DECLARE
  v_is_boleta BOOLEAN;
  v_boleta_id BIGINT;
BEGIN
  -- Determinar si la bÃºsqueda es un nÃºmero (boleta) o texto (cÃ©dula)
  v_is_boleta := (p_query ~ '^\d+$');

  IF v_is_boleta THEN
    v_boleta_id := p_query::BIGINT;
  END IF;

  RETURN QUERY
  SELECT
    b.id_boleta,
    ('TKN-' || LPAD(b.id_boleta::TEXT, 6, '0'))::TEXT AS token_boleta,
    b.estado::SMALLINT,
    CASE b.estado
      WHEN 0 THEN 'ðŸ“¦ Bodega'
      WHEN 1 THEN 'ðŸšš Despachada al Distribuidor'
      WHEN 2 THEN 'ðŸª Activa en Comercio'
      WHEN 3 THEN 'âœ… Registrada por Cliente'
      WHEN 4 THEN 'âŒ Anulada / Fraude'
      ELSE 'â“ Desconocido'
    END::TEXT AS estado_label,
    -- QuiÃ©n despachÃ³
    pa.nombre::TEXT AS asignado_por_nombre,
    pa.rol::TEXT AS asignado_por_rol,
    -- Distribuidor
    pd.nombre::TEXT AS distribuidor_nombre,
    z.nombre::TEXT AS distribuidor_zona,
    pd.movil::TEXT AS distribuidor_movil,
    -- Comercio
    b.comercio_nombre::TEXT AS comercio_nombre,
    b.zona_comercio::TEXT AS zona_comercio,
    b.fecha_despacho,
    b.fecha_activacion,
    -- Cliente (campos existentes de la tabla boletas)
    b.nombre_usuario::TEXT AS nombre_cliente,
    b.identificacion_usuario::TEXT AS cedula_cliente,
    b.celular_usuario::TEXT AS telefono_cliente,
    b.fecha_registro,
    -- Premio
    pr.nombre_premio::TEXT AS premio_nombre
  FROM public.boletas b
  LEFT JOIN public.perfiles pa ON b.asignado_por = pa.id
  LEFT JOIN public.perfiles pd ON b.distribuidor_id = pd.id
  LEFT JOIN public.zonas z ON pd.zona_id = z.id
  LEFT JOIN public.premios pr ON b.premio_seleccionado = pr.id
  WHERE
    (v_is_boleta AND (
      b.id_boleta = v_boleta_id 
      OR b.token_integridad = ('TKN-' || LPAD(p_query, 6, '0'))
    ))
    OR
    (NOT v_is_boleta AND (
      b.token_integridad ILIKE '%' || p_query || '%'
      OR b.identificacion_usuario ILIKE '%' || p_query || '%'
    ))
  ORDER BY b.id_boleta
  LIMIT 20;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Actualizar asignar_lote_boletas para registrar quiÃ©n asignÃ³
CREATE OR REPLACE FUNCTION asignar_lote_boletas(p_admin_id UUID, p_dist_id UUID, p_rango_inicio BIGINT, p_rango_fin BIGINT)
RETURNS INTEGER AS $$
DECLARE
    tiene_permiso BOOLEAN;
    filas_afectadas INTEGER;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM public.perfiles 
        WHERE id = p_admin_id AND rol IN ('admin', 'operativo')
    ) INTO tiene_permiso;
    
    IF NOT tiene_permiso THEN
        RAISE EXCEPTION 'SEGURIDAD: OperaciÃ³n denegada. Sin permisos de asignaciÃ³n.';
    END IF;

    UPDATE public.boletas 
    SET 
        estado = 1,
        distribuidor_id = p_dist_id,
        asignado_por = p_admin_id       -- Trazabilidad: registrar quiÃ©n despachÃ³
    WHERE id_boleta BETWEEN p_rango_inicio AND p_rango_fin
      AND estado = 0;

    GET DIAGNOSTICS filas_afectadas = ROW_COUNT;
    RETURN filas_afectadas;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- =====================================================================
-- MigraciÃ³n: MÃ³dulo de Ingreso Masivo a Bodega
-- =====================================================================

-- RPC para crear lotes de boletas de forma eficiente en el servidor
-- p_inicio y p_fin definen el rango numÃ©rico (ej: 1 a 100,000)
CREATE OR REPLACE FUNCTION crear_lote_bodega(
  p_inicio BIGINT, 
  p_fin BIGINT, 
  p_campana_id UUID
)
RETURNS INTEGER AS $$
DECLARE
    filas_creadas INTEGER;
BEGIN
    -- ValidaciÃ³n de seguridad bÃ¡sica en los argumentos
    IF p_inicio < 0 OR p_fin <= p_inicio THEN
        RAISE EXCEPTION 'PARÃMETROS INVÃLIDOS: El rango debe ser positivo y el fin mayor al inicio.';
    END IF;

    -- InserciÃ³n masiva optimizada: generate_series es Ã³rdenes de magnitud mÃ¡s rÃ¡pido que 
    -- realizar mÃºltiples llamadas individuales desde la API de Edge Functions/Actions.
    INSERT INTO public.boletas (
      id_boleta, 
      token_integridad, 
      campana_id, 
      estado,
      -- Forzamos limpieza de campos logÃ­sticos y de cliente por seguridad
      distribuidor_id,
      comercio_nombre,
      identificacion_usuario,
      nombre_usuario,
      celular_usuario,
      habeas_data_aceptado,
      premio_seleccionado,
      fecha_activacion,
      fecha_registro
    )
    SELECT 
        s.val,
        'TKN-' || LPAD(s.val::TEXT, 6, '0'), -- 6 dÃ­gitos: 000001
        p_campana_id,
        0, -- Estado Inicial Obligatorio: 0 (Bodega)
        NULL, NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL
    FROM generate_series(p_inicio, p_fin) AS s(val)
    ON CONFLICT (id_boleta) DO NOTHING; -- InserciÃ³n resiliente: Ignorar existentes
    
    GET DIAGNOSTICS filas_creadas = ROW_COUNT;
    RETURN filas_creadas;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comentario de auditorÃ­a para el dashboard
COMMENT ON FUNCTION crear_lote_bodega IS 'Genera masivamente boletas en Estado 0 para carga inicial de inventario.';
-- â”€â”€ SEMILLAS DE UNIDADES TERRITORIALES (COMUNAS) â”€â”€
-- MisiÃ³n: Robustez GeogrÃ¡fica Comunas 1-7

-- Insertar Comunas si no existen
INSERT INTO zonas (nombre)
VALUES 
  ('Comuna 1'),
  ('Comuna 2'),
  ('Comuna 3'),
  ('Comuna 4'),
  ('Comuna 5'),
  ('Comuna 6'),
  ('Comuna 7')
ON CONFLICT (nombre) DO NOTHING;

-- Nota: Si la tabla 'zonas' tiene una restricciÃ³n UNIQUE en 'nombre', el ON CONFLICT funcionarÃ¡.
-- Si el ID es serial, se autogenerarÃ¡. 
-- â”€â”€ MOTORES LOGÃSTICOS (RPC) â”€â”€
-- MisiÃ³n: AutomatizaciÃ³n y Control de Bodega

-- 1. VALIDAR RANGO DE BOLETAS
-- Verifica que un bloque estÃ© Ã­ntegramente en Bodega (Estado 0)
CREATE OR REPLACE FUNCTION public.validar_rango_boletas(p_inicio integer, p_fin integer)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_total integer;
    v_disponibles integer;
    v_no_aptas integer;
    v_es_valido boolean;
BEGIN
    v_total := (p_fin - p_inicio) + 1;
    
    SELECT count(*) INTO v_disponibles
    FROM boletas
    WHERE id_boleta BETWEEN p_inicio AND p_fin
    AND estado = 0;
    
    v_no_aptas := v_total - v_disponibles;
    v_es_valido := (v_no_aptas = 0);
    
    RETURN json_build_object(
        'total_solicitado', v_total,
        'disponibles_en_rango', v_disponibles,
        'no_aptas', v_no_aptas,
        'es_valido', v_es_valido
    );
END;
$$;

-- 2. SUGERIR PRÃ“XIMO LOTE
-- Encuentra el primer bloque continuo disponible de tamaÃ±o X
CREATE OR REPLACE FUNCTION public.sugerir_proximo_lote(p_tamano integer DEFAULT 100)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_inicio integer;
    v_fin integer;
BEGIN
    -- Buscamos el ID inicial mÃ¡s bajo que estÃ© en estado 0
    SELECT min(id_boleta) INTO v_inicio
    FROM boletas
    WHERE estado = 0;
    
    IF v_inicio IS NULL THEN
        RETURN json_build_object('success', false);
    END IF;
    
    v_fin := v_inicio + p_tamano - 1;
    
    RETURN json_build_object(
        'success', true,
        'sugerido_inicio', v_inicio,
        'sugerido_fin', v_fin
    );
END;
$$;

-- 3. ASIGNAR LOTE DE BOLETAS (TRANSACCIONAL)
-- Ejecuta el despacho masivo y registra el lote logÃ­stico
CREATE OR REPLACE FUNCTION public.asignar_lote_boletas(
    p_admin_id uuid,
    p_dist_id uuid,
    p_rango_inicio integer,
    p_rango_fin integer,
    p_zona_id uuid
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_rows_affected integer;
    v_campana_id text;
BEGIN
    -- Obtenemos el ID de campaÃ±a de la primera boleta del rango (asumiendo homogeneidad)
    SELECT campana_id INTO v_campana_id
    FROM boletas
    WHERE id_boleta = p_rango_inicio
    LIMIT 1;

    -- A. Actualizar Estado de Boletas (Estado 1: Despachada)
    UPDATE boletas
    SET 
        estado = 1,
        perfil_id = p_dist_id,
        zona_id = p_zona_id,
        updated_at = now()
    WHERE id_boleta BETWEEN p_rango_inicio AND p_rango_fin
    AND estado = 0;
    
    GET DIAGNOSTICS v_rows_affected = ROW_COUNT;
    
    -- B. Registrar Lote LogÃ­stico (AuditorÃ­a de Despacho)
    IF v_rows_affected > 0 THEN
        INSERT INTO lotes_logisticos (
            admin_id,
            distribuidor_id,
            rango_inicio,
            rango_fin,
            cantidad,
            estado_lote,
            zona_id,
            campana_id
        ) VALUES (
            p_admin_id,
            p_dist_id,
            p_rango_inicio,
            p_rango_fin,
            v_rows_affected,
            'despachado',
            p_zona_id,
            v_campana_id
        );
    END IF;
    
    RETURN v_rows_affected;
END;
$$;
-- =====================================================================
-- MigraciÃ³n: MÃ³dulo de AnulaciÃ³n e Inmutabilidad de Boletas
-- =====================================================================

-- 1. ActualizaciÃ³n de la MÃ¡quina de Estados Estricta
CREATE OR REPLACE FUNCTION auditar_estado_boleta()
RETURNS TRIGGER AS $$
BEGIN
    -- BLOQUEO TOTAL: Si una boleta ya estÃ¡ ANULADA (4), es inmutable.
    IF OLD.estado = 4 AND NEW.estado != 4 THEN
        RAISE EXCEPTION 'BLOQUEO DE SEGURIDAD: La boleta % ya estÃ¡ ANULADA y no puede ser reactivada ni modificada.', OLD.id_boleta;
    END IF;

    -- LÃ³gica de transiciÃ³n a ANULADA (4)
    -- Se permite anular desde cualquier estado previo (0, 1, 2, 3) 
    -- esto permite invalidar inventario en bodega, despachado o incluso premios fraudulentos.
    IF NEW.estado = 4 AND OLD.estado != 4 THEN
        -- Registrar fecha de anulaciÃ³n (opcional, usamos updated_at por defecto)
        -- NEW.updated_at = NOW(); -- Ya se hace al final
    END IF;

    -- LÃ³gica de transiciÃ³n de estado hacia DESPACHADA (1)
    IF NEW.estado = 1 THEN
        IF OLD.estado != 0 AND OLD.estado != 1 THEN -- Permitir re-despacho si ya era 1
            RAISE EXCEPTION 'MÃQUINA DE ESTADOS: Boleta % no puede ser DESPACHADA si no estaba en BODEGA (0).', NEW.id_boleta;
        END IF;
        IF NEW.distribuidor_id IS NULL THEN
            RAISE EXCEPTION 'LOGÃSTICA: Boleta % despachada sin distribuidor asignado.', NEW.id_boleta;
        END IF;
        IF OLD.estado = 0 THEN
            NEW.fecha_despacho = NOW();
        END IF;
    END IF;

    -- Estado 2 (Activa en Comercio): Viene de 1
    IF NEW.estado = 2 THEN
        IF OLD.estado != 1 AND OLD.estado != 2 THEN
            RAISE EXCEPTION 'MÃQUINA DE ESTADOS: Boleta % no puede ser ACTIVA sin haber sido despachada previamente (Estado 1).', NEW.id_boleta;
        END IF;
        IF NEW.comercio_nombre IS NULL THEN
            RAISE EXCEPTION 'LOGÃSTICA: Falta el nombre del comercio final para activar boleta %.', NEW.id_boleta;
        END IF;
        IF OLD.estado = 1 THEN
            NEW.fecha_activacion = NOW();
        END IF;
    END IF;

    -- LÃ³gica de transiciÃ³n de estado hacia REGISTRADA (3)
    IF NEW.estado = 3 THEN
        IF OLD.estado != 2 THEN
            RAISE EXCEPTION 'ViolaciÃ³n de SEGURIDAD: La boleta % no puede ser REGISTRADA sin estar previamente ACTIVA en punto de venta. Estado anterior: %', NEW.id_boleta, OLD.estado;
        END IF;
        IF NEW.habeas_data_aceptado IS NOT TRUE THEN
            RAISE EXCEPTION 'ViolaciÃ³n de POLÃTICA DE DATOS: La boleta % requiere la aceptaciÃ³n expresa de las polÃ­ticas de privacidad y tratamiento de datos (Ley 1581).', NEW.id_boleta;
        END IF;
        IF NEW.premio_seleccionado IS NULL THEN
            RAISE EXCEPTION 'ViolaciÃ³n de REGLA NEGOCIO: La boleta % no ha seleccionado un premio dinÃ¡mico.', NEW.id_boleta;
        END IF;
        NEW.fecha_registro = NOW();
    END IF;

    -- ActualizaciÃ³n de Ãºltimo cambio
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. RPC para anulaciÃ³n administrativa con auditorÃ­a
CREATE OR REPLACE FUNCTION anular_boleta(p_admin_id UUID, p_boleta_id BIGINT)
RETURNS BOOLEAN AS $$
DECLARE
    tiene_permiso BOOLEAN;
BEGIN
    -- Solo admin u operativo puede anular
    SELECT EXISTS (
        SELECT 1 FROM public.perfiles 
        WHERE id = p_admin_id AND rol IN ('admin', 'operativo')
    ) INTO tiene_permiso;
    
    IF NOT tiene_permiso THEN
        RAISE EXCEPTION 'SEGURIDAD: OperaciÃ³n denegada. Sin permisos de anulaciÃ³n.';
    END IF;

    UPDATE public.boletas 
    SET 
        estado = 4 -- ANULADA
    WHERE id_boleta = p_boleta_id;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- =====================================================================
-- MigraciÃ³n: MÃ³dulo de Sorteos e Inmutabilidad de ParticipaciÃ³n
-- =====================================================================

-- 1. EvoluciÃ³n de la Tabla Boletas (Estado 5)
-- Modificar el constraint existente para permitir el estado 5 (Sorteada)
ALTER TABLE public.boletas DROP CONSTRAINT IF EXISTS boletas_estado_check;
ALTER TABLE public.boletas ADD CONSTRAINT boletas_estado_check CHECK (estado BETWEEN 0 AND 5);

-- 2. Nueva Tabla de Sorteos
CREATE TABLE IF NOT EXISTS public.sorteos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    premio_id UUID REFERENCES public.premios(id) ON DELETE CASCADE,
    fecha_sorteo TIMESTAMPTZ NOT NULL,
    estado TEXT NOT NULL DEFAULT 'programado' CHECK (estado IN ('programado', 'finalizado')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS en sorteos
ALTER TABLE public.sorteos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura publica de sorteos" ON public.sorteos FOR SELECT USING (true);
CREATE POLICY "Admin gestiona sorteos" ON public.sorteos FOR ALL USING (
    EXISTS (SELECT 1 FROM public.perfiles WHERE id = auth.uid() AND rol = 'admin')
);

-- 3. MÃ¡quina de Estados Estricta (Blindaje Final)
CREATE OR REPLACE FUNCTION auditar_estado_boleta()
RETURNS TRIGGER AS $$
BEGIN
    -- BLOQUEO TOTAL: Si una boleta ya fue SORTEADA (5) o ANULADA (4), es inmutable.
    IF OLD.estado IN (4, 5) AND NEW.estado != OLD.estado THEN
        RAISE EXCEPTION 'BLOQUEO DE SEGURIDAD: La boleta % ya estÃ¡ en un estado final (%) y no puede ser modificada.', OLD.id_boleta, OLD.estado;
    END IF;

    -- LÃ³gica de transiciÃ³n a SORTEADA (5): Solo viene de REGISTRADA (3)
    IF NEW.estado = 5 THEN
        IF OLD.estado != 3 THEN
            RAISE EXCEPTION 'MÃQUINA DE ESTADOS: Boleta % no puede marcarse como SORTEADA si no estaba REGISTRADA (3).', NEW.id_boleta;
        END IF;
    END IF;

    -- LÃ³gica de transiciÃ³n a ANULADA (4): Se permite desde cualquier estado previo (0-3)
    IF NEW.estado = 4 AND OLD.estado NOT IN (4, 5) THEN
        -- Permitir anulaciÃ³n
    END IF;

    -- Estado 1 (Despachada): Viene de 0
    IF NEW.estado = 1 THEN
        IF OLD.estado != 0 AND OLD.estado != 1 THEN
            RAISE EXCEPTION 'MÃQUINA DE ESTADOS: Boleta % no puede ser DESPACHADA si no estaba en BODEGA (0).', NEW.id_boleta;
        END IF;
        IF NEW.distribuidor_id IS NULL THEN
            RAISE EXCEPTION 'LOGÃSTICA: Boleta % despachada sin distribuidor asignado.', NEW.id_boleta;
        END IF;
    END IF;

    -- Estado 2 (Activa): Viene de 1
    IF NEW.estado = 2 THEN
        IF OLD.estado != 1 AND OLD.estado != 2 THEN
            RAISE EXCEPTION 'MÃQUINA DE ESTADOS: Boleta % no puede ser ACTIVA sin haber sido despachada previamente (Estado 1).', NEW.id_boleta;
        END IF;
    END IF;

    -- Estado 3 (Registrada): Viene de 2
    IF NEW.estado = 3 THEN
        IF OLD.estado != 2 THEN
            RAISE EXCEPTION 'ViolaciÃ³n de SEGURIDAD: La boleta % no puede ser REGISTRADA sin estar previamente ACTIVA. Estado anterior: %', NEW.id_boleta, OLD.estado;
        END IF;
        IF NEW.habeas_data_aceptado IS NOT TRUE THEN
            RAISE EXCEPTION 'ViolaciÃ³n de POLÃTICA DE DATOS: AceptaciÃ³n de Habeas Data requerida.';
        END IF;
        IF NEW.premio_seleccionado IS NULL THEN
            RAISE EXCEPTION 'ViolaciÃ³n de REGLA NEGOCIO: SelecciÃ³n de premio obligatoria.';
        END IF;
        NEW.fecha_registro = NOW();
    END IF;

    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. RPC para Cierre de Sorteo Masivo
CREATE OR REPLACE FUNCTION cerrar_sorteo_campana(p_admin_id UUID, p_campana_id UUID)
RETURNS INTEGER AS $$
DECLARE
    tiene_permiso BOOLEAN;
    filas_afectadas INTEGER;
BEGIN
    -- AuditorÃ­a DB-First: Solo admin puede cerrar sorteos
    SELECT EXISTS (
        SELECT 1 FROM public.perfiles 
        WHERE id = p_admin_id AND rol = 'admin'
    ) INTO tiene_permiso;
    
    IF NOT tiene_permiso THEN
        RAISE EXCEPTION 'SEGURIDAD: OperaciÃ³n denegada. Sin permisos de cierre de sorteo.';
    END IF;

    -- Mover todas las boletas registradas (3) al estado final (5)
    UPDATE public.boletas 
    SET 
        estado = 5 -- SORTEADA
    WHERE campana_id = p_campana_id
      AND estado = 3;

    GET DIAGNOSTICS filas_afectadas = ROW_COUNT;
    RETURN filas_afectadas;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- =====================================================================
-- MigraciÃ³n: Inteligencia GeogrÃ¡fica y Trazabilidad Geo-Espacial
-- =====================================================================

-- 1. Tabla de CatÃ¡logo de Territorios (Barrios/Corregimientos)
CREATE TABLE IF NOT EXISTS public.territorios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre VARCHAR(255) UNIQUE NOT NULL,
    tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('Barrio', 'Corregimiento', 'Municipio')),
    padre_id UUID REFERENCES public.territorios(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Territorios: Lectura PÃºblica
ALTER TABLE public.territorios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura publica de territorios" ON public.territorios FOR SELECT USING (true);

-- 2. EvoluciÃ³n de la Tabla Boletas
ALTER TABLE public.boletas 
    ADD COLUMN IF NOT EXISTS ubicacion_cliente_id UUID REFERENCES public.territorios(id),
    ADD COLUMN IF NOT EXISTS zona_id UUID REFERENCES public.zonas(id);

-- Ãndices Geo
CREATE INDEX IF NOT EXISTS idx_boletas_territorio ON public.boletas(ubicacion_cliente_id);
CREATE INDEX IF NOT EXISTS idx_boletas_zona_id ON public.boletas(zona_id);

-- 3. Tabla de Trazabilidad GeogrÃ¡fica (BitÃ¡cora de Movimiento)
CREATE TABLE IF NOT EXISTS public.trazabilidad_geografica (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    boleta_id BIGINT REFERENCES public.boletas(id_boleta),
    estado_destino SMALLINT NOT NULL,
    ubicacion_nombre VARCHAR(255),
    zona_id UUID REFERENCES public.zonas(id),
    distribuidor_id UUID REFERENCES public.perfiles(id),
    ip_evento INET,
    fecha_evento TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Trazabilidad: Solo Admin e Internal
ALTER TABLE public.trazabilidad_geografica ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admin lee trazabilidad" ON public.trazabilidad_geografica FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.perfiles WHERE id = auth.uid() AND rol = 'admin')
);

-- 4. FuniÃ³n Auditora Mejorada (Historial AutomÃ¡tico)
CREATE OR REPLACE FUNCTION auditar_estado_boleta()
RETURNS TRIGGER AS $$
DECLARE
    v_zona_id UUID;
    v_ubicacion_text VARCHAR;
BEGIN
    -- BLOQUEO TOTAL: Inmutabilidad Estados Finales
    IF OLD.estado IN (4, 5) AND NEW.estado != OLD.estado THEN
        RAISE EXCEPTION 'BLOQUEO DE SEGURIDAD: Boleta % ya estÃ¡ en estado final (%).', OLD.id_boleta, OLD.estado;
    END IF;

    -- REGISTRO DE TRAZABILIDAD GEOGRÃFICA (BitÃ¡cora automÃ¡tica)
    -- Si el estado cambiÃ³, insertamos el "salto" de ubicaciÃ³n
    IF (NEW.estado != OLD.estado) OR (OLD.estado IS NULL) THEN
        
        -- Definir contexto de ubicaciÃ³n para el log
        CASE NEW.estado
            WHEN 0 THEN v_ubicacion_text := 'Bodega Central Palmira';
            WHEN 1 THEN v_ubicacion_text := 'En TrÃ¡nsito (Distribuidor)';
            WHEN 2 THEN v_ubicacion_text := COALESCE(NEW.comercio_nombre, 'Punto de Venta');
            WHEN 3 THEN v_ubicacion_text := 'Registrada por Cliente';
            WHEN 4 THEN v_ubicacion_text := 'Anulada Administrativamente';
            WHEN 5 THEN v_ubicacion_text := 'ParticipÃ³ en Sorteo';
            ELSE v_ubicacion_text := 'Trazabilidad Interna';
        END CASE;

        INSERT INTO public.trazabilidad_geografica (
            boleta_id,
            estado_destino,
            ubicacion_nombre,
            zona_id,
            distribuidor_id,
            ip_evento
        ) VALUES (
            NEW.id_boleta,
            NEW.estado,
            v_ubicacion_text,
            COALESCE(NEW.zona_id, (SELECT zona_id FROM perfiles WHERE id = NEW.distribuidor_id)),
            NEW.distribuidor_id,
            NEW.ip_registro
        );
    END IF;

    -- LÃ³gica de transiciÃ³n a SORTEADA (5)
    IF NEW.estado = 5 AND OLD.estado != 3 THEN
        RAISE EXCEPTION 'MÃQUINA DE ESTADOS: Requiere estar REGISTRADA (3).';
    END IF;

    -- Estado 2 (Activa): Viene de 1
    IF NEW.estado = 2 AND OLD.estado != 1 THEN
        -- Nota: activar_boleta_comercio ya se encarga de setear zona_id y comercio_nombre
    END IF;

    -- Estado 3 (Registrada): Viene de 2
    IF NEW.estado = 3 THEN
        IF OLD.estado != 2 THEN
            RAISE EXCEPTION 'ViolaciÃ³n de SEGURIDAD: Requiere estar previamente ACTIVA.';
        END IF;
        IF NEW.habeas_data_aceptado IS NOT TRUE THEN
            RAISE EXCEPTION 'Habeas Data obligatorio.';
        END IF;
        IF NEW.premio_seleccionado IS NULL THEN
            RAISE EXCEPTION 'Premio obligatorio.';
        END IF;
        IF NEW.ubicacion_cliente_id IS NULL THEN
            RAISE EXCEPTION 'Territorio (Barrio) de residencia obligatorio.';
        END IF;
        NEW.fecha_registro = NOW();
    END IF;

    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. Actualizar RPC activar_boleta_comercio
CREATE OR REPLACE FUNCTION activar_boleta_comercio(p_dist_id UUID, p_boleta_id BIGINT, p_nombre_comercio VARCHAR)
RETURNS BOOLEAN AS $$
DECLARE
    filas_afectadas INTEGER;
    v_zona_id UUID;
    v_zona_nombre VARCHAR;
BEGIN
    -- Capturar Zona del Distribuidor
    SELECT z.id, z.nombre INTO v_zona_id, v_zona_nombre 
    FROM public.perfiles p
    JOIN public.zonas z ON p.zona_id = z.id
    WHERE p.id = p_dist_id LIMIT 1;

    UPDATE public.boletas 
    SET 
        estado = 2,
        comercio_nombre = p_nombre_comercio,
        zona_comercio = v_zona_nombre, -- Mantenemos por compatibilidad visual actual
        zona_id = v_zona_id
    WHERE id_boleta = p_boleta_id
      AND distribuidor_id = p_dist_id
      AND estado = 1;

    GET DIAGNOSTICS filas_afectadas = ROW_COUNT;
    
    IF filas_afectadas = 0 THEN
        RAISE EXCEPTION 'No se pudo activar la boleta.';
    END IF;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- MigraciÃ³n: Soporte para UbicaciÃ³n Manual (Campo OTRO)
ALTER TABLE public.boletas 
    ADD COLUMN IF NOT EXISTS ubicacion_manual TEXT;

COMMENT ON COLUMN public.boletas.ubicacion_manual IS 'Almacena el nombre del barrio cuando el usuario selecciona la opciÃ³n OTRO.';
-- =====================================================================
-- MigraciÃ³n: Blindaje Legal (Ley 1581) y TÃ©rminos y Condiciones
-- =====================================================================

-- 1. EvoluciÃ³n de la Tabla Boletas con Campos Legales
ALTER TABLE public.boletas 
    ADD COLUMN IF NOT EXISTS acepta_terminos BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS fecha_aceptacion_terminos TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS version_terminos TEXT DEFAULT 'v1.0-abril-2026';

-- Nota: ip_registro ya existe de migraciones previas (geo_inteligencia)

-- 2. ActualizaciÃ³n de Comentarios para AuditorÃ­a
COMMENT ON COLUMN public.boletas.acepta_terminos IS 'Indica si el usuario aceptÃ³ debidamente los T&C y Habeas Data.';
COMMENT ON COLUMN public.boletas.fecha_aceptacion_terminos IS 'Marca de tiempo del servidor al momento del registro.';
COMMENT ON COLUMN public.boletas.version_terminos IS 'VersiÃ³n inmutable de los tÃ©rminos vigentes al momento del registro.';

-- 3. Refuerzo de la FunciÃ³n Auditora (Triggers de Seguridad)
CREATE OR REPLACE FUNCTION auditar_estado_boleta()
RETURNS TRIGGER AS $$
DECLARE
    v_zona_id UUID;
    v_ubicacion_text VARCHAR;
BEGIN
    -- BLOQUEO TOTAL: Inmutabilidad Estados Finales (4: ANULADA, 5: SORTEADA)
    IF OLD.estado IN (4, 5) AND NEW.estado != OLD.estado THEN
        RAISE EXCEPTION 'BLOQUEO DE SEGURIDAD: Boleta % ya estÃ¡ en estado final (%).', OLD.id_boleta, OLD.estado;
    END IF;

    -- REGISTRO DE TRAZABILIDAD GEOGRÃFICA (BitÃ¡cora automÃ¡tica)
    IF (NEW.estado != OLD.estado) OR (OLD.estado IS NULL) THEN
        CASE NEW.estado
            WHEN 0 THEN v_ubicacion_text := 'Bodega Central Palmira';
            WHEN 1 THEN v_ubicacion_text := 'En TrÃ¡nsito (Distribuidor)';
            WHEN 2 THEN v_ubicacion_text := COALESCE(NEW.comercio_nombre, 'Punto de Venta');
            WHEN 3 THEN v_ubicacion_text := 'Registrada por Cliente';
            WHEN 4 THEN v_ubicacion_text := 'Anulada Administrativamente';
            WHEN 5 THEN v_ubicacion_text := 'ParticipÃ³ en Sorteo';
            ELSE v_ubicacion_text := 'Trazabilidad Interna';
        END CASE;

        INSERT INTO public.trazabilidad_geografica (
            boleta_id,
            estado_destino,
            ubicacion_nombre,
            zona_id,
            distribuidor_id,
            ip_evento
        ) VALUES (
            NEW.id_boleta,
            NEW.estado,
            v_ubicacion_text,
            COALESCE(NEW.zona_id, (SELECT zona_id FROM perfiles WHERE id = NEW.distribuidor_id)),
            NEW.distribuidor_id,
            NEW.ip_registro
        );
    END IF;

    -- MÃQUINA DE ESTADOS: LÃ³gica de Negocio
    IF NEW.estado = 3 THEN
        IF OLD.estado != 2 THEN
            RAISE EXCEPTION 'ViolaciÃ³n de SEGURIDAD: Requiere estar previamente ACTIVA en punto de venta.';
        END IF;

        -- BLINDAJE LEGAL: Validaciones Ley 1581 (Habeas Data)
        IF NEW.acepta_terminos IS NOT TRUE THEN
            RAISE EXCEPTION 'BLOQUEO LEGAL: El registro requiere la aceptaciÃ³n explÃ­cita de los TÃ©rminos y Condiciones.';
        END IF;
        
        IF NEW.fecha_aceptacion_terminos IS NULL THEN
            NEW.fecha_aceptacion_terminos = NOW();
        END IF;

        IF NEW.premio_seleccionado IS NULL THEN
            RAISE EXCEPTION 'Requisito comercial: Debe seleccionar un premio de la lista.';
        END IF;

        IF NEW.ubicacion_cliente_id IS NULL THEN
            RAISE EXCEPTION 'Error de ubicaciÃ³n: El barrio o corregimiento de residencia es obligatorio.';
        END IF;

        -- Registro de fecha de conversiÃ³n
        NEW.fecha_registro = NOW();
    END IF;

    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- =====================================================================
-- MigraciÃ³n: Identidad Visual (Fotos de Premios)
-- =====================================================================

-- 1. EvoluciÃ³n de la Tabla Premios
ALTER TABLE public.premios 
    ADD COLUMN IF NOT EXISTS imagen_url TEXT;

COMMENT ON COLUMN public.premios.imagen_url IS 'URL pÃºblica de la fotografÃ­a oficial del premio en Supabase Storage.';

-- 2. Infraestructura de Storage (Bucket)
-- Nota: Supabase requiere polÃ­ticas RLS para lectura pÃºblica
INSERT INTO storage.buckets (id, name, public) 
VALUES ('fotos-premios', 'fotos-premios', true)
ON CONFLICT (id) DO NOTHING;

-- PolÃ­tica de Lectura PÃºblica (Permite que cualquier usuario vea las fotos)
CREATE POLICY "Fotos Premios Lectura PÃºblica"
ON storage.objects FOR SELECT
USING (bucket_id = 'fotos-premios');

-- PolÃ­tica de InserciÃ³n para Administradores (vÃ­a Service Role o Autenticados)
CREATE POLICY "Admin Upload Fotos"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'fotos-premios');
-- =====================================================================
-- CorrecciÃ³n: PolÃ­ticas RLS de Storage para fotos-premios
-- =====================================================================

-- 1. Eliminar polÃ­ticas previas para evitar conflictos
DROP POLICY IF EXISTS "Fotos Premios Lectura PÃºblica" ON storage.objects;
DROP POLICY IF EXISTS "Admin Upload Fotos" ON storage.objects;

-- 2. PolÃ­tica de Lectura PÃºblica Universal
CREATE POLICY "Acceso PÃºblico Lectura"
ON storage.objects FOR SELECT
USING (bucket_id = 'fotos-premios');

-- 3. PolÃ­tica de GestiÃ³n Total para Usuarios Autenticados (Admins)
-- Se usa FOR ALL para permitir INSERT, UPDATE y DELETE
CREATE POLICY "Admin Full Access"
ON storage.objects FOR ALL
TO authenticated
USING (bucket_id = 'fotos-premios')
WITH CHECK (bucket_id = 'fotos-premios');

-- 4. Asegurar que el bucket sea pÃºblico y activo
UPDATE storage.buckets 
SET public = true 
WHERE id = 'fotos-premios';
-- =====================================================================
-- MisiÃ³n: Blindaje Total de Storage (fotos-premios)
-- =====================================================================

-- 1. Asegurar existencia y visibilidad pÃºblica del bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('fotos-premios', 'fotos-premios', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 2. Limpieza de PolÃ­ticas Previas (Evitar solapamientos)
DROP POLICY IF EXISTS "Acceso PÃºblico Lectura" ON storage.objects;
DROP POLICY IF EXISTS "Admin Full Access" ON storage.objects;
DROP POLICY IF EXISTS "Fotos Premios Lectura PÃºblica" ON storage.objects;
DROP POLICY IF EXISTS "Admin Upload Fotos" ON storage.objects;

-- 3. POLÃTICA DE INSERCIÃ“N (UPLOAD):
-- Permite subir archivos a usuarios autenticados (JWT vÃ¡lido) y al rol service_role (Admin Bypass)
CREATE POLICY "Permitir Upload a Admin"
ON storage.objects FOR INSERT
TO authenticated, service_role
WITH CHECK (bucket_id = 'fotos-premios');

-- 4. POLÃTICA DE LECTURA (SELECT):
-- Permite visualizaciÃ³n pÃºblica universal (Sin Login) para la Landing Page
CREATE POLICY "Permitir Lectura PÃºblica Universal"
ON storage.objects FOR SELECT
USING (bucket_id = 'fotos-premios');

-- 5. POLÃTICA DE GESTIÃ“N (UPDATE/DELETE):
-- Permite al Admin modificar o borrar fotos existentes
CREATE POLICY "Permitir GestiÃ³n Total a Admin"
ON storage.objects FOR ALL
TO authenticated, service_role
USING (bucket_id = 'fotos-premios')
WITH CHECK (bucket_id = 'fotos-premios');
-- =====================================================================
-- ReparaciÃ³n Nuclear: ConfiguraciÃ³n Total de Storage (fotos-premios)
-- =====================================================================

-- 1. Asegurar existencia y configuraciÃ³n pÃºblica absoluta del bucket
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) 
VALUES ('fotos-premios', 'fotos-premios', true, 5242880, '{image/*}')
ON CONFLICT (id) DO UPDATE SET public = true, file_size_limit = 5242880, allowed_mime_types = '{image/*}';

-- 2. Limpieza Radical de PolÃ­ticas (Eliminar cualquier rastro de conflictos)
DROP POLICY IF EXISTS "Permitir Upload a Admin" ON storage.objects;
DROP POLICY IF EXISTS "Permitir Lectura PÃºblica Universal" ON storage.objects;
DROP POLICY IF EXISTS "Permitir GestiÃ³n Total a Admin" ON storage.objects;
DROP POLICY IF EXISTS "Acceso PÃºblico Lectura" ON storage.objects;
DROP POLICY IF EXISTS "Admin Full Access" ON storage.objects;
DROP POLICY IF EXISTS "Fotos Premios Lectura PÃºblica" ON storage.objects;
DROP POLICY IF EXISTS "Admin Upload Fotos" ON storage.objects;
DROP POLICY IF EXISTS "Acceso PÃºblico Universal" ON storage.objects;

-- 3. POLÃTICA DE ACCESO TOTAL (SELECT, INSERT, UPDATE, DELETE)
-- Se permite a TODOS los roles (public, authenticated, service_role)
-- Esto garantiza que la subida funcione en desarrollo local sin importar el estado de la sesiÃ³n
CREATE POLICY "Acceso Total fotos-premios"
ON storage.objects FOR ALL
USING (bucket_id = 'fotos-premios')
WITH CHECK (bucket_id = 'fotos-premios');

-- Fin del script de reparaciÃ³n nuclear
-- =====================================================================
-- MigraciÃ³n: Branding DinÃ¡mico (Llaves Maestras)
-- =====================================================================

-- 1. EvoluciÃ³n de la Tabla ConfiguraciÃ³n
ALTER TABLE public.configuracion_campana 
    ADD COLUMN IF NOT EXISTS slogan_principal TEXT DEFAULT 'Blindaje Legal y Transparencia: Registra tus datos para participar oficialmente.',
    ADD COLUMN IF NOT EXISTS logo_url TEXT;

COMMENT ON COLUMN public.configuracion_campana.slogan_principal IS 'Slogan o bajada legal que aparece en el Hero de la Landing Page.';
COMMENT ON COLUMN public.configuracion_campana.logo_url IS 'URL pÃºblica del logotipo de la campaÃ±a alojado en Supabase Storage.';
-- =====================================================================
-- MigraciÃ³n: LÃ­mites y PolÃ­ticas de Storage (ProducciÃ³n)
-- Contenido consolidado para asegurar integridad en despliegue.
-- =====================================================================

-- 1. Asegurar existencia y configuraciÃ³n del bucket 'fotos-premios'
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('fotos-premios', 'fotos-premios', true, 5242880, '{image/*}')
ON CONFLICT (id) DO UPDATE SET 
    public = true, 
    file_size_limit = 5242880, 
    allowed_mime_types = '{image/*}';

-- 2. Limpieza de PolÃ­ticas Previas (Evitar conflictos en despliegue)
DROP POLICY IF EXISTS "Acceso Total fotos-premios" ON storage.objects;
DROP POLICY IF EXISTS "Permitir Upload a Admin" ON storage.objects;
DROP POLICY IF EXISTS "Permitir Lectura PÃºblica Universal" ON storage.objects;
DROP POLICY IF EXISTS "Permitir GestiÃ³n Total a Admin" ON storage.objects;
DROP POLICY IF EXISTS "Public Full Access" ON storage.objects;

-- 3. POLÃTICA DE LECTURA PÃšBLICA (SELECT)
-- Crucial para que la Landing Page visualice las imÃ¡genes sin login.
CREATE POLICY "Lectura PÃºblica Premios"
ON storage.objects FOR SELECT
USING (bucket_id = 'fotos-premios');

-- 4. POLÃTICAS DE GESTIÃ“N ADMINISTRATIVA (INSERT, UPDATE, DELETE)
-- Restringido a usuarios autenticados (Dashboard Admin) o service_role.

-- InserciÃ³n (Subida)
CREATE POLICY "Admin Subida Premios"
ON storage.objects FOR INSERT
TO authenticated, service_role
WITH CHECK (bucket_id = 'fotos-premios');

-- ActualizaciÃ³n (Reemplazo)
CREATE POLICY "Admin ActualizaciÃ³n Premios"
ON storage.objects FOR UPDATE
TO authenticated, service_role
USING (bucket_id = 'fotos-premios')
WITH CHECK (bucket_id = 'fotos-premios');

-- EliminaciÃ³n (Borrado)
CREATE POLICY "Admin EliminaciÃ³n Premios"
ON storage.objects FOR DELETE
TO authenticated, service_role
USING (bucket_id = 'fotos-premios');
-- =====================================================================
-- MigraciÃ³n: Zona Operativa Central
-- =====================================================================

INSERT INTO public.zonas (nombre, descripcion, activa)
VALUES ('Nacional / Bodega Central', 'Zona logÃ­stica maestra para personal operativo y administrativo central.', true)
ON CONFLICT (nombre) DO NOTHING;
-- =====================================================================
-- MigraciÃ³n: Blindaje de Inventario y ValidaciÃ³n en Tiempo Real
-- =====================================================================

-- 1. FunciÃ³n para validar disponibilidad de un rango (Auditada)
CREATE OR REPLACE FUNCTION validar_rango_boletas(p_inicio BIGINT, p_fin BIGINT)
RETURNS TABLE (
    total_solicitado BIGINT,
    disponibles_en_rango BIGINT,
    no_aptas BIGINT,
    es_valido BOOLEAN
) AS $$
DECLARE
    v_total BIGINT;
    v_disp BIGINT;
BEGIN
    -- Validar rangos bÃ¡sicos
    IF p_inicio > p_fin THEN
        v_total := 0;
        v_disp := 0;
    ELSE
        v_total := (p_fin - p_inicio) + 1;
        
        -- Contar boletas que estÃ¡n fÃ­sicamente en bodega (0) y sin dueÃ±o
        SELECT COUNT(*) INTO v_disp
        FROM public.boletas
        WHERE id_boleta BETWEEN p_inicio AND p_fin
          AND estado = 0
          AND distribuidor_id IS NULL;
    END IF;

    RETURN QUERY SELECT 
        v_total, 
        v_disp, 
        (v_total - v_disp) as no_aptas,
        (v_total > 0 AND v_total = v_disp) as es_valido;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. FunciÃ³n para sugerir el prÃ³ximo bloque disponible
CREATE OR REPLACE FUNCTION sugerir_proximo_lote(p_tamano INTEGER DEFAULT 100)
RETURNS TABLE (
    sugerido_inicio BIGINT,
    sugerido_fin BIGINT
) AS $$
DECLARE
    v_inicio BIGINT;
BEGIN
    -- Encontrar el ID de boleta mÃ¡s bajo que aÃºn estÃ© en bodega y libre
    SELECT id_boleta INTO v_inicio
    FROM public.boletas
    WHERE estado = 0 AND distribuidor_id IS NULL
    ORDER BY id_boleta ASC
    LIMIT 1;

    IF v_inicio IS NOT NULL THEN
        -- Sugerir un bloque del tamaÃ±o solicitado (default 100)
        RETURN QUERY SELECT v_inicio, v_inicio + p_tamano - 1;
    ELSE
        RETURN QUERY SELECT NULL::BIGINT, NULL::BIGINT;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Comentario de AuditorÃ­a
COMMENT ON FUNCTION validar_rango_boletas IS 'Verifica disponibilidad fÃ­sica de boletas en bodega antes de asignar.';
COMMENT ON FUNCTION sugerir_proximo_lote IS 'Busca el primer hueco virgen en el inventario para sugerir al operador.';
-- =====================================================================
-- MigraciÃ³n: AuditorÃ­a Detallada e InformaciÃ³n Bajo Demanda
-- =====================================================================

-- 1. EvoluciÃ³n de la Tabla Boletas: Responsable de Origen
ALTER TABLE public.boletas ADD COLUMN IF NOT EXISTS asignado_por UUID REFERENCES public.perfiles(id);

-- 2. Actualizar FunciÃ³n Auditora: Sincronizar Asignado Por
CREATE OR REPLACE FUNCTION auditar_estado_boleta_v2()
RETURNS TRIGGER AS $$
DECLARE
    v_zona_id UUID;
    v_ubicacion_text VARCHAR;
BEGIN
    -- [MÃQUINA DE ESTADOS ORIGINAL]
    IF OLD.estado IN (4, 5) AND NEW.estado != OLD.estado THEN
        RAISE EXCEPTION 'BLOQUEO DE SEGURIDAD: Boleta % ya estÃ¡ en estado final.', OLD.id_boleta;
    END IF;

    -- Si se asigna un distribuidor (Paso a Estado 1), capturar quiÃ©n lo hizo
    -- Nota: asignar_lote_boletas ya setea asignado_por, pero por si acaso lo reforzamos.
    
    -- [TRAZABILIDAD GEOGRÃFICA]
    IF (NEW.estado != OLD.estado) OR (OLD.estado IS NULL) THEN
        CASE NEW.estado
            WHEN 0 THEN v_ubicacion_text := 'Bodega Central Palmira';
            WHEN 1 THEN v_ubicacion_text := 'En TrÃ¡nsito (Distribuidor)';
            WHEN 2 THEN v_ubicacion_text := COALESCE(NEW.comercio_nombre, 'Punto de Venta');
            WHEN 3 THEN v_ubicacion_text := 'Registrada por Cliente';
            WHEN 4 THEN v_ubicacion_text := 'Anulada Administrativamente';
            WHEN 5 THEN v_ubicacion_text := 'ParticipÃ³ en Sorteo';
            ELSE v_ubicacion_text := 'Trazabilidad Interna';
        END CASE;

        INSERT INTO public.trazabilidad_geografica (
            boleta_id, estado_destino, ubicacion_nombre, zona_id, distribuidor_id, ip_evento
        ) VALUES (
            NEW.id_boleta, NEW.estado, v_ubicacion_text, 
            COALESCE(NEW.zona_id, (SELECT zona_id FROM perfiles WHERE id = NEW.distribuidor_id)),
            NEW.distribuidor_id, NEW.ip_registro
        );
    END IF;

    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. RPC para Resumen de Inventario por Distribuidor
CREATE OR REPLACE FUNCTION get_resumen_inventario_distribuidor(p_dist_id UUID)
RETURNS TABLE (
    total_asignado BIGINT,
    total_activado BIGINT,
    total_registrado BIGINT,
    p_conversion NUMERIC
) AS $$
BEGIN
    RETURN QUERY 
    SELECT 
        COUNT(*) as total_asignado,
        COUNT(*) FILTER (WHERE estado >= 2) as total_activado,
        COUNT(*) FILTER (WHERE estado >= 3) as total_registrado,
        CASE 
            WHEN COUNT(*) FILTER (WHERE estado >= 2) = 0 THEN 0.0
            ELSE ROUND((COUNT(*) FILTER (WHERE estado >= 3)::NUMERIC / COUNT(*) FILTER (WHERE estado >= 2)::NUMERIC) * 100, 1)
        END as p_conversion
    FROM public.boletas
    WHERE distribuidor_id = p_dist_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. RPC para AgrupaciÃ³n de Lotes (Rangos)
CREATE OR REPLACE FUNCTION get_lotes_distribuidor(p_dist_id UUID)
RETURNS TABLE (
    rango_inicio BIGINT,
    rango_fin BIGINT,
    cantidad BIGINT,
    fecha_asignacion TIMESTAMPTZ
) AS $$
BEGIN
    -- Agrupamos trazabilidad por saltos de ID o tiempo similar
    -- Para este demo, usaremos una lÃ³gica de islas y huecos simplificada
    RETURN QUERY
    WITH diffs AS (
        SELECT 
            boleta_id,
            fecha_evento,
            boleta_id - ROW_NUMBER() OVER (ORDER BY boleta_id) as grp
        FROM public.trazabilidad_geografica
        WHERE distribuidor_id = p_dist_id AND estado_destino = 1
    )
    SELECT 
        MIN(boleta_id) as rango_inicio,
        MAX(boleta_id) as rango_fin,
        COUNT(*) as cantidad,
        MIN(fecha_evento) as fecha_asignacion
    FROM diffs
    GROUP BY grp
    ORDER BY fecha_asignacion DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- =====================================================================
-- MigraciÃ³n: MÃ³dulo de Ventas y Cumplimiento Legal (Habeas Data)
-- =====================================================================

-- 1. Tabla: Ventas a Clientes Finales
CREATE TABLE IF NOT EXISTS public.ventas_clientes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    boleta_id BIGINT UNIQUE REFERENCES public.boletas(id_boleta),
    cliente_id VARCHAR(50) NOT NULL, -- CÃ©dula/DNI
    cliente_nombre VARCHAR(255) NOT NULL,
    cliente_movil VARCHAR(50) NOT NULL,
    comercio_nombre VARCHAR(255) NOT NULL,
    distribuidor_id UUID REFERENCES public.perfiles(id),
    
    -- Cumplimiento Legal
    acepta_tratamiento_datos BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_consentimiento TIMESTAMPTZ DEFAULT NOW(),
    canal_consentimiento TEXT DEFAULT 'App Distribuidor',
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices para auditorÃ­a veloz
CREATE INDEX idx_ventas_cliente_id ON public.ventas_clientes(cliente_id);
CREATE INDEX idx_ventas_distribuidor ON public.ventas_clientes(distribuidor_id);
CREATE INDEX idx_ventas_boleta ON public.ventas_clientes(boleta_id);

-- 2. RLS: Reporte de Ventas
ALTER TABLE public.ventas_clientes ENABLE ROW LEVEL SECURITY;

-- Los administradores y operativos pueden ver todo el reporte
CREATE POLICY "Admin/Operativo pueden ver todas las ventas" 
ON public.ventas_clientes FOR SELECT 
USING ((SELECT rol FROM perfiles WHERE id = auth.uid()) IN ('admin', 'operativo'));

-- Los distribuidores pueden ver sus propias ventas realizadas
CREATE POLICY "Distribuidores ven sus propias ventas" 
ON public.ventas_clientes FOR SELECT 
USING (distribuidor_id = auth.uid());

-- 3. AuditorÃ­a: SincronizaciÃ³n con Trazabilidad (Trigger Opcional)
-- Nota: La acciÃ³n de servidor insertarÃ¡ aquÃ­ directamente tras activar.

COMMENT ON TABLE public.ventas_clientes IS 'Registro de compradores finales y consentimiento de Habeas Data recolectado en campo.';
-- =====================================================================
-- MigraciÃ³n: AdiciÃ³n de Campos GeogrÃ¡ficos a Ventas (DirecciÃ³n y Barrio)
-- =====================================================================

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'ventas_clientes' AND column_name = 'cliente_direccion'
    ) THEN
        ALTER TABLE public.ventas_clientes ADD COLUMN cliente_direccion VARCHAR(255);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'ventas_clientes' AND column_name = 'cliente_barrio'
    ) THEN
        ALTER TABLE public.ventas_clientes ADD COLUMN cliente_barrio VARCHAR(255);
    END IF;
END $$;

COMMENT ON COLUMN public.ventas_clientes.cliente_direccion IS 'DirecciÃ³n de residencia del comprador final.';
COMMENT ON COLUMN public.ventas_clientes.cliente_barrio IS 'Barrio o corregimiento del comprador final (mapeado desde tabla territorios).';
-- =====================================================================
-- MigraciÃ³n: Arquitectura Multizona y Multi-lote (N:N y Trazabilidad)
-- =====================================================================

-- 1. Tabla Intermedia: Perfil - Zonas (Muchos a Muchos)
CREATE TABLE IF NOT EXISTS public.perfil_zonas (
    perfil_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
    zona_id UUID REFERENCES public.zonas(id) ON DELETE CASCADE,
    PRIMARY KEY (perfil_id, zona_id)
);

-- 2. EvoluciÃ³n de Boletas: Trazabilidad por Destino EspecÃ­fico
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'boletas' AND column_name = 'zona_destino_id'
    ) THEN
        ALTER TABLE public.boletas ADD COLUMN zona_destino_id UUID REFERENCES public.zonas(id);
    END IF;
END $$;

-- 3. MigraciÃ³n de Datos (Legacy to Modern)
-- Mover la zona_id actual de perfiles a la nueva tabla perfil_zonas
INSERT INTO public.perfil_zonas (perfil_id, zona_id)
SELECT id, zona_id FROM public.perfiles 
WHERE zona_id IS NOT NULL
ON CONFLICT DO NOTHING;

-- 4. Actualizar asignar_lote_boletas para registrar Zona de Destino
CREATE OR REPLACE FUNCTION asignar_lote_boletas(
    p_admin_id UUID, 
    p_dist_id UUID, 
    p_rango_inicio BIGINT, 
    p_rango_fin BIGINT,
    p_zona_id UUID -- Nueva variable obligatoria
)
RETURNS INTEGER AS $$
DECLARE
    tiene_permiso BOOLEAN;
    filas_afectadas INTEGER;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM public.perfiles 
        WHERE id = p_admin_id AND rol IN ('admin', 'operativo')
    ) INTO tiene_permiso;
    
    IF NOT tiene_permiso THEN
        RAISE EXCEPTION 'SEGURIDAD: OperaciÃ³n denegada. Sin permisos de asignaciÃ³n.';
    END IF;

    UPDATE public.boletas 
    SET 
        estado = 1,
        distribuidor_id = p_dist_id,
        asignado_por = p_admin_id,
        zona_destino_id = p_zona_id -- Registrar destino estratÃ©gico
    WHERE id_boleta BETWEEN p_rango_inicio AND p_rango_fin
      AND estado = 0;

    GET DIAGNOSTICS filas_afectadas = ROW_COUNT;
    RETURN filas_afectadas;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Actualizar activar_boleta_comercio para usar la Zona de Destino
CREATE OR REPLACE FUNCTION activar_boleta_comercio(p_dist_id UUID, p_boleta_id BIGINT, p_nombre_comercio VARCHAR)
RETURNS BOOLEAN AS $$
DECLARE
    filas_afectadas INTEGER;
    v_zona_nombre VARCHAR;
BEGIN
    -- Priorizar la zona de destino grabada en la boleta; fallback a la primera zona del perfil
    SELECT z.nombre INTO v_zona_nombre 
    FROM public.boletas b
    JOIN public.zonas z ON b.zona_destino_id = z.id
    WHERE b.id_boleta = p_boleta_id 
    LIMIT 1;

    -- Si no hay zona_destino (legacy), buscar herencia del perfil
    IF v_zona_nombre IS NULL THEN
        SELECT z.nombre INTO v_zona_nombre 
        FROM public.perfil_zonas pz
        JOIN public.zonas z ON pz.zona_id = z.id
        WHERE pz.perfil_id = p_dist_id 
        LIMIT 1;
    END IF;

    UPDATE public.boletas 
    SET 
        estado = 2,
        comercio_nombre = p_nombre_comercio,
        zona_comercio = v_zona_nombre
    WHERE id_boleta = p_boleta_id
      AND distribuidor_id = p_dist_id
      AND estado = 1;

    GET DIAGNOSTICS filas_afectadas = ROW_COUNT;
    
    IF filas_afectadas = 0 THEN
        RAISE EXCEPTION 'No se pudo activar la boleta. Verifique que no haya sido activada ya, o que usted sea su propietario.';
    END IF;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON TABLE public.perfil_zonas IS 'RelaciÃ³n N:N para permitir que agentes cubran mÃºltiples zonas territoriales.';
COMMENT ON COLUMN public.boletas.zona_destino_id IS 'ID de la zona especÃ­fica para la cual se despachÃ³ este lote fÃ­sico.';

-- 6. Consultas de AuditorÃ­a Multizona
CREATE OR REPLACE FUNCTION get_lotes_distribuidor(p_dist_id UUID)
RETURNS TABLE (
    rango_inicio BIGINT,
    rango_fin BIGINT,
    cantidad BIGINT,
    fecha_asignacion TIMESTAMPTZ,
    zona_nombre VARCHAR
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        MIN(b.id_boleta) as rango_inicio,
        MAX(b.id_boleta) as rango_fin,
        COUNT(*)::BIGINT as cantidad,
        MIN(b.updated_at) as fecha_asignacion,
        z.nombre as zona_nombre
    FROM public.boletas b
    LEFT JOIN public.zonas z ON b.zona_destino_id = z.id
    WHERE b.distribuidor_id = p_dist_id
      AND b.estado >= 1
    GROUP BY b.distribuidor_id, b.zona_destino_id, z.nombre, b.asignado_por, date_trunc('minute', b.updated_at)
    ORDER BY fecha_asignacion DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_resumen_multizona(p_dist_id UUID)
RETURNS TABLE (
    zona_nombre VARCHAR,
    total_asignado BIGINT,
    total_activado BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        z.nombre as zona_nombre,
        COUNT(*)::BIGINT as total_asignado,
        COUNT(*) FILTER (WHERE b.estado >= 2)::BIGINT as total_activado
    FROM public.boletas b
    JOIN public.zonas z ON b.zona_destino_id = z.id
    WHERE b.distribuidor_id = p_dist_id
    GROUP BY z.nombre;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- =====================================================================
-- Fix: RLS para Tabla Perfil-Zonas y Acceso de Red LogÃ­stica
-- =====================================================================

-- 1. Habilitar RLS en la tabla intermedia
ALTER TABLE public.perfil_zonas ENABLE ROW LEVEL SECURITY;

-- 2. PolÃ­ticas de Lectura
-- Todos los usuarios autenticados pueden ver las asignaciones de zona (necesario para joins en el dashboard)
CREATE POLICY "Lectura Autenticada Perfil Zonas" 
ON public.perfil_zonas FOR SELECT 
USING (auth.role() = 'authenticated');

-- 3. PolÃ­ticas de GestiÃ³n (Solo Admin)
CREATE POLICY "GestiÃ³n Admin Perfil Zonas" 
ON public.perfil_zonas FOR ALL 
USING ((SELECT rol FROM public.perfiles WHERE id = auth.uid()) = 'admin');

COMMENT ON POLICY "Lectura Autenticada Perfil Zonas" ON public.perfil_zonas IS 'Permite que distribuidores y operativos consulten su propia red de zonas asignadas.';
-- =====================================================================
-- SEED SQL: La Villa del MillÃ³n 2026 (Palmira Digital)
-- Fuente de Verdad para Datos Maestros y Entorno de Desarrollo
-- =====================================================================

-- 1. ConfiguraciÃ³n de CampaÃ±a (Fiel al Dashboard "Llaves Maestras")
INSERT INTO public.configuracion_campana (id, nombre_campana, landing_slug, activa, slogan_principal, logo_url)
VALUES (
    '11111111-1111-1111-1111-111111111111', 
    'La Villa del MillÃ³n 2026', 
    'villa-millon-2026', 
    true, 
    'Blindaje Legal y Transparencia: Registra tus datos para participar oficialmente.',
    'https://raw.githubusercontent.com/supabase-community/supabase-logos/main/supabase-logo-icon.png' -- Placeholder
) ON CONFLICT (id) DO UPDATE SET
    nombre_campana = EXCLUDED.nombre_campana,
    slogan_principal = EXCLUDED.slogan_principal;

-- 2. Zonas Comerciales EstratÃ©gicas
INSERT INTO public.zonas (id, nombre, descripcion) VALUES 
('44444444-4444-4444-4444-444444444444', 'Nacional / Bodega Central', 'Sede principal de distribuciÃ³n y gerencia administrativa.'),
('55555555-5555-5555-5555-555555555555', 'Zona 1 - Centro HistÃ³rico', 'Cobertura comercial calle 30 a 33.'),
('66666666-6666-6666-6666-666666666666', 'Zona 2 - Versalles / Norte', 'Corredor comercial AV 19.'),
('55555555-5555-5555-5555-555555555556', 'Rozo - Sector Parques', 'DistribuciÃ³n principal en plaza de Rozo.')
ON CONFLICT (nombre) DO UPDATE SET 
    id = EXCLUDED.id,
    descripcion = EXCLUDED.descripcion;

-- 3. CatÃ¡logo de Premios (Los 4 Grandes)
INSERT INTO public.premios (id, campana_id, nombre_premio, descripcion, cantidad_disponible, imagen_url)
VALUES 
('77777777-7777-7777-7777-777777777777', '11111111-1111-1111-1111-111111111111', 'Carro Kia Sportage 0km', 'El gran premio final para dinamizar tu vida.', 1, 'https://images.unsplash.com/photo-1632243193741-b308fd45167a?auto=format&fit=crop&q=80&w=800'),
('88888888-8888-8888-8888-888888888888', '11111111-1111-1111-1111-111111111111', 'Moto Yamaha MT-09', 'Siente el poder de la velocidad Palmira.', 2, 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&q=80&w=800'),
('00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'Bono de $1 MillÃ³n COP', 'VÃ¡lido en comercios aliados de la ciudad.', 50, 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?auto=format&fit=crop&q=80&w=800'),
('99999999-9999-9999-9999-999999999999', '11111111-1111-1111-1111-111111111111', 'Viaje a San AndrÃ©s', 'Paquete todo incluido para 2 personas.', 5, 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800')
ON CONFLICT (id) DO NOTHING;

-- 4. Territorios Palmira (Barrios y Corregimientos)
INSERT INTO public.territorios (nombre, tipo) VALUES 
-- Comuna 1
('Zamorano', 'Barrio'), ('Harold Ã‰der', 'Barrio'), ('Coronado', 'Barrio'), ('Los Caimitos', 'Barrio'), 
('Villa del Rosario', 'Barrio'), ('20 de Julio', 'Barrio'), ('Camilo Torres', 'Barrio'), 
('La Vega', 'Barrio'), ('Villa Diana', 'Barrio'), ('SimÃ³n BolÃ­var', 'Barrio'), 
('Ignacio Torres', 'Barrio'), ('Molinos 100', 'Barrio'), ('Brisas del Norte', 'Barrio'), 
('Bosques del EdÃ©n', 'Barrio'), ('UrbanizaciÃ³n Los Mangos', 'Barrio'),
-- Comuna 2
('BerlÃ­n', 'Barrio'), ('Santa MarÃ­a del Palmar', 'Barrio'), ('La Orlidia', 'Barrio'), 
('Juan Pablo II', 'Barrio'), ('Estonia', 'Barrio'), ('Versalles', 'Barrio'), 
('MirriÃ±ao', 'Barrio'), ('Villa Claudia', 'Barrio'), ('Santa Teresita', 'Barrio'), 
('Altamira', 'Barrio'), ('Cristales', 'Barrio'),
-- Comuna 3
('El Prado', 'Barrio'), ('La Emilia', 'Barrio'), ('Llanogrande', 'Barrio'), 
('Fray Luis AmigÃ³', 'Barrio'), ('Santa Ana', 'Barrio'), ('OlÃ­mpico', 'Barrio'), 
('Jorge EliÃ©cer GaitÃ¡n (C3)', 'Barrio'), ('Brisas del Bolo', 'Barrio'), 
('La Concordia', 'Barrio'), ('Las Acacias', 'Barrio'), ('Pomona', 'Barrio'), 
('Santa BÃ¡rbara', 'Barrio'), ('Rivera Escobar', 'Barrio'), 
('UrbanizaciÃ³n Villa de las Palmas', 'Barrio'), ('Alicanto', 'Barrio'),
-- Comuna 4
('Colombia', 'Barrio'), ('Jorge EliÃ©cer GaitÃ¡n (C4)', 'Barrio'), ('Loreto', 'Barrio'), 
('Alfonso LÃ³pez', 'Barrio'), ('Bizerta', 'Barrio'), ('Uribe Uribe', 'Barrio'), 
('Obrero', 'Barrio'), ('San Cayetano', 'Barrio'), ('Chapinero Sur', 'Barrio'), 
('Santa Rita', 'Barrio'),
-- Comuna 5
('San Pedro', 'Barrio'), ('Primero de Mayo', 'Barrio'), ('Danubio', 'Barrio'), 
('La Libertad', 'Barrio'), ('San Carlos', 'Barrio'), ('Providencia', 'Barrio'), 
('El Campestre', 'Barrio'), ('San Jorge', 'Barrio'), ('Palmeras de Oriente', 'Barrio'), 
('Siete de Agosto', 'Barrio'), ('El JardÃ­n', 'Barrio'), ('El Bosque', 'Barrio'), 
('MarÃ­a Cano', 'Barrio'), ('Popular Modelo', 'Barrio'), ('Municipal', 'Barrio'), 
('Los Sauces', 'Barrio'), ('San JosÃ©', 'Barrio'), ('JosÃ© Antonio GalÃ¡n', 'Barrio'), 
('Prados de Oriente', 'Barrio'), ('Palmeras de Marsella', 'Barrio'),
-- Comuna 6
('Caicelandia', 'Barrio'), ('FÃ¡tima', 'Barrio'), ('El Triunfo', 'Barrio'), 
('Ciudadela Palmira', 'Barrio'), ('UrbanizaciÃ³n Las Flores', 'Barrio'), 
('Central', 'Barrio'), ('Colombina', 'Barrio'), ('Libertadores', 'Barrio'), 
('UrbanizaciÃ³n El ParaÃ­so', 'Barrio'), ('La Trinidad', 'Barrio'),
-- Comuna 7
('La Italia', 'Barrio'), ('Tulipanes de la Italia', 'Barrio'), ('Brisas de la Italia', 'Barrio'), 
('Reserva de la Italia', 'Barrio'), ('Luis Carlos GalÃ¡n', 'Barrio'), ('Barrio Nuevo', 'Barrio'), 
('Las Delicias', 'Barrio'), ('El Recreo', 'Barrio'), ('Santa Clara', 'Barrio'), 
('UrbanizaciÃ³n Petruc', 'Barrio'),
-- Corregimientos
('Rozo', 'Corregimiento'), ('Amaime', 'Corregimiento'), ('El Bolo', 'Corregimiento'), 
('Tienda Nueva', 'Corregimiento'), ('Palmaseca', 'Corregimiento'), ('Guanabanal', 'Corregimiento'), 
('La Acequia', 'Corregimiento'), ('La Torre', 'Corregimiento'), ('Tablones', 'Corregimiento'),
('OTRO', 'Municipio')
ON CONFLICT (nombre) DO NOTHING;

-- 5. Identidades QA (IAM)
-- Admite: admin_qas@villa.com, distribuidor_qas@villa.com, operativo_qas@villa.com (Pass: password123)
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, 
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, 
    email_change, email_change_token_new, recovery_token
) VALUES 
('00000000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222222', 'authenticated', 'authenticated', 'admin_qas@villa.com', extensions.crypt('password123', extensions.gen_salt('bf')), NOW(), '{"provider":"email","providers":["email"]}', '{}', NOW(), NOW(), '', '', '', ''),
('00000000-0000-0000-0000-000000000000', '33333333-3333-3333-3333-333333333333', 'authenticated', 'authenticated', 'distribuidor_qas@villa.com', extensions.crypt('password123', extensions.gen_salt('bf')), NOW(), '{"provider":"email","providers":["email"]}', '{}', NOW(), NOW(), '', '', '', ''),
('00000000-0000-0000-0000-000000000000', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'authenticated', 'authenticated', 'operativo_qas@villa.com', extensions.crypt('password123', extensions.gen_salt('bf')), NOW(), '{"provider":"email","providers":["email"]}', '{}', NOW(), NOW(), '', '', '', '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at, id) 
VALUES 
('22222222-2222-2222-2222-222222222222', '22222222-2222-2222-2222-222222222222', format('{"sub":"22222222-2222-2222-2222-222222222222","email":"%s"}', 'admin_qas@villa.com')::jsonb, 'email', NOW(), NOW(), NOW(), '22222222-2222-2222-2222-222222222222'),
('33333333-3333-3333-3333-333333333333', '33333333-3333-3333-3333-333333333333', format('{"sub":"33333333-3333-3333-3333-333333333333","email":"%s"}', 'distribuidor_qas@villa.com')::jsonb, 'email', NOW(), NOW(), NOW(), '33333333-3333-3333-3333-333333333333'),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', format('{"sub":"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa","email":"%s"}', 'operativo_qas@villa.com')::jsonb, 'email', NOW(), NOW(), NOW(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')
ON CONFLICT DO NOTHING;

-- 6. Perfiles QAS (Base de Datos)
INSERT INTO public.perfiles (id, nombre, rol, zona_id, cedula, movil) VALUES 
('22222222-2222-2222-2222-222222222222', 'Gerencia Palmira 2026', 'admin', '44444444-4444-4444-4444-444444444444', '11111111', '3001111111'),
('33333333-3333-3333-3333-333333333333', 'Distribuidor Rozo', 'distribuidor', '55555555-5555-5555-5555-555555555556', '33333333', '3103333333'),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Operativo LogÃ­stico', 'operativo', '44444444-4444-4444-4444-444444444444', '99999999', '3209999999')
ON CONFLICT (id) DO NOTHING;

-- 7. Inventario Inicial (Boletas en Bodega)
INSERT INTO public.boletas (id_boleta, estado, token_integridad, campana_id) 
SELECT 
    i, 
    0, 
    'TKN-' || LPAD(i::TEXT, 6, '0'), 
    '11111111-1111-1111-1111-111111111111'
FROM generate_series(1, 100) AS i
ON CONFLICT DO NOTHING;
