-- Migración Inicial para Campaña de Dinamización (Supabase PostgreSQL)
-- Cumplimiento de requerimientos: 1-5M registros, Máquina de estados, Ley 1581 (Habeas Data).

-- 1. Tabla de Configuración de Campaña
CREATE TABLE public.configuracion_campana (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre_campana VARCHAR(255) NOT NULL,
    landing_slug VARCHAR(255) UNIQUE NOT NULL,
    activa BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Premios (Inyección Dinámica)
-- Permite que el Dashboard administre los premios y el frontend consulte en tiempo real.
CREATE TABLE public.premios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campana_id UUID REFERENCES public.configuracion_campana(id) ON DELETE CASCADE,
    nombre_premio VARCHAR(255) NOT NULL,
    descripcion TEXT,
    cantidad_disponible INTEGER NOT NULL DEFAULT 0 CHECK (cantidad_disponible >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Boletas (Optimizada para 5M de registros)
-- Estados: 0=CREADA, 1=IMPRESA, 2=ACTIVA, 3=REGISTRADA, 4=CERRADA
CREATE TABLE public.boletas (
    id_boleta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campana_id UUID REFERENCES public.configuracion_campana(id),
    
    -- Uso de SMALLINT con CHECK constraint en lugar de Enum para eficiencia en búsquedas sobre millones de filas.
    estado SMALLINT NOT NULL DEFAULT 0 CHECK (estado BETWEEN 0 AND 4),
    
    -- Token único de integridad para prevenir ataques
    token_integridad VARCHAR(255) UNIQUE NOT NULL,
    
    -- Campos capturados en el proceso
    identificacion_usuario VARCHAR(50),
    nombre_usuario VARCHAR(255),
    celular_usuario VARCHAR(20),
    
    -- Checkbox obligatorio Habeas Data (Ley 1581 Colombiana)
    habeas_data_aceptado BOOLEAN DEFAULT false,
    
    -- Premio seleccionado inyectado en el Landing
    premio_seleccionado UUID REFERENCES public.premios(id),
    
    -- Datos operativos para ranking y analítica
    zona_comercio VARCHAR(255),
    ip_registro INET,
    
    -- Trazabilidad de tiempos
    fecha_activacion TIMESTAMPTZ,
    fecha_registro TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices B-Tree eficientes para lectura con volúmenes de 5M+ de filas
CREATE INDEX idx_boletas_estado ON public.boletas(estado);
CREATE INDEX idx_boletas_token ON public.boletas(token_integridad);
CREATE INDEX idx_boletas_campana ON public.boletas(campana_id);

-- 4. Función y Máquina de Estados (Triple Candado de Seguridad)
CREATE OR REPLACE FUNCTION auditar_estado_boleta()
RETURNS TRIGGER AS $$
BEGIN
    -- Lógica de transición de estado hacia REGISTRADA (3)
    IF NEW.estado = 3 THEN
        
        -- Candado 1: El estado inmediatamente anterior DEBE ser ACTIVA (2)
        IF OLD.estado != 2 THEN
            RAISE EXCEPTION 'Violación de SEGURIDAD: La boleta % no puede ser REGISTRADA sin estar previamente ACTIVA en punto de venta. Estado anterior: %', NEW.id_boleta, OLD.estado;
        END IF;

        -- Candado 2: Cumplimiento Ley 1581 (Habeas Data) obligatorio
        IF NEW.habeas_data_aceptado IS NOT TRUE THEN
            RAISE EXCEPTION 'Violación de POLÍTICA DE DATOS: La boleta % requiere la aceptación expresa de las políticas de privacidad y tratamiento de datos (Ley 1581).', NEW.id_boleta;
        END IF;

        -- Candado 3: Selección de premio obligatoria (consulta al menú desplegable)
        IF NEW.premio_seleccionado IS NULL THEN
            RAISE EXCEPTION 'Violación de REGLA NEGOCIO: La boleta % no ha seleccionado un premio dinámico.', NEW.id_boleta;
        END IF;

        -- Setear el timestamp exacto del registro
        NEW.fecha_registro = NOW();
    END IF;

    -- Registrar Timestamp cuando se activa la boleta (Estado 2)
    IF NEW.estado = 2 AND OLD.estado != 2 THEN
        NEW.fecha_activacion = NOW();
    END IF;

    -- Actualización de último cambio
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. Trigger
CREATE TRIGGER trg_maquina_estados_boletas
BEFORE UPDATE ON public.boletas
FOR EACH ROW
EXECUTE FUNCTION auditar_estado_boleta();

-- 6. Configuración de Seguridad RLS
ALTER TABLE public.configuracion_campana ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.premios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boletas ENABLE ROW LEVEL SECURITY;

-- Políticas de Lectura (Edge Access)
-- Permite que el Landing Page consulte campañas activas
CREATE POLICY "Lectura pública de configuracion activa" 
ON public.configuracion_campana FOR SELECT USING (activa = true);

-- Permite consultar los premios disponibles solo de las campañas activas
CREATE POLICY "Lectura pública de premios disponibles" 
ON public.premios FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.configuracion_campana 
        WHERE id = premios.campana_id AND activa = true
    )
);

-- Acceso cerrado al cliente: Boletas solo se consultan/registran a través de 
-- Supabase Edge Functions con la llave 'Service Role'
CREATE POLICY "Boletas bloqueadas a lectura anonima" 
ON public.boletas FOR ALL USING (false);
